Repository BiblioTroca/BiblioTrocaFrontEnd, pull requests merged in 2023-11, with the labels that each got.

#40 Pull Request da Develop para Main
  package.json
  src/app/perfil/lista-desejos/novo-desejo/page.tsx
  src/app/perfil/meus-livros/cadastrar-livro/page.tsx
  src/lib/axios.ts
Labels: bug, refactor

#41 Adicionando Hotjar para UX Heatmap
  .gitignore
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
  src/app/perfil/historico/troca/[id]/page.tsx
  src/app/perfil/trocas-pendentes/troca/[id]/page.tsx
  src/components/Button.tsx
  src/styles/globals.css
Labels: feat

#42 Pull Request para consertar os problemas do Hotjar
  .gitignore
  public/scripts/hotjar.js
Labels: bug

#44 🔀 Integração inicial com o backend e exibição de contagem na home
  package.json
  pnpm-lock.yaml
  src/@types/bookSimpleData.ts
  src/@types/sellerData.ts
  src/app/components/AboutUs.tsx
  src/app/livro/[id]/components/ContentBook.tsx
  src/app/livro/[id]/components/RequestBook.tsx
  src/app/livro/[id]/page.tsx
  src/app/livros/components/BookCard.tsx
  src/app/livros/components/BookList.tsx
  src/app/livros/components/HeroBanner.tsx
  src/app/livros/page.tsx
  src/app/login/page.tsx
  src/app/page.tsx
  src/app/perfil/historico/troca/[id]/page.tsx
  src/app/perfil/lista-desejos/page.tsx
  src/app/perfil/meus-livros/page.tsx
  src/app/perfil/trocas-pendentes/page.tsx
  src/app/perfil/trocas-pendentes/troca/[id]/page.tsx
  src/components/Modal/DeleteAccountModal.tsx
  src/components/Modal/DeleteBookModal.tsx
  src/components/Modal/EvaluateModal.tsx
  src/components/Modal/RefuseExchangeModal.tsx
  src/components/Modal/RequestExchangeModal.tsx
  src/components/Modal/index.tsx
  src/components/PublicHeader/MobilePublicHeader.tsx
  src/components/PublicHeader/SessionButton.tsx
  src/components/PublicHeader/SwitchTheme.tsx
  src/components/PublicHeader/index.tsx
  src/contexts/QueryContext.tsx
  src/hooks/useBooks.ts
  src/hooks/useTransaction.ts
  src/lib/axios.ts
  src/utils/auth.ts
Labels: bug, refactor, feat
